name: Build and Push Rust Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: publish docker image
      uses: flamestro/build-push-github-action@v1.7.4
      with:
        username: ${{ github.repository_owner }}
        token: ${{ secrets.GITHUB_TOKEN }}
        image: ${{ github.repository_owner }}/helloworld
        tags: latest
        dockerfile: Dockerfile
