name: Build and Push Rust Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    # - name: Build Docker image
    #   run: docker build -t docker.pkg.github.com/draju1980/rusthelloworld/helloworld:VERSION .
    # - name: Login to GitHub Docker Registry
    #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    # - name: Push Docker image
    #   run: docker push docker.pkg.github.com/draju1980/rusthelloworld/helloworld:VERSION
